INSERT INTO user(user_name, password, first_name, last_name, role, locked) VALUE ('admin', 'mNy+OfwBVzPj9442CM86ANCQGd0=', 'Manager', 'Jaconin', 'MANAGER', FALSE);

INSERT INTO category VALUES
	(1, "Áo thun"),
    (2, "Áo khoác"),
    (3, "Quần dài"),
    (4, "Quần ngắn"),
    (5, "Sơ mi");

INSERT INTO product(product_id, description, image, name, price, size, title, category_id) VALUES
	(1, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(2, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(3, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(4, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(5, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(6, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(7, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(8, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(9, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(10, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5),
    (11, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(12, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(13, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(14, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(15, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(16, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(17, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(18, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(19, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(20, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5),
    (21, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(22, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(23, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(24, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(25, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(26, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(27, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(28, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(29, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(30, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5),
    (31, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(32, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(33, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(34, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(35, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(36, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(37, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(38, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(39, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(40, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5),
    (41, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(42, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(43, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(44, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(45, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(46, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(47, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(48, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(49, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(50, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5),
    (51, "Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.", "/img/product/1.png", "Áo thun Jaco_X1", 220000, "X", "Áo thun đơn giản", 1),
	(52, "Sản phẩm thoáng mát, có độ bền tốt.", "/img/product/1.png", "Áo thun ABC", 250000, "XL", "Áo thun thiết kế", 1),
	(53, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Jaco", 360000, "XXL", "Áo khoác Jean", 2),
	(54, "Sản phẩm thoáng mát", "/img/product/2.png", "Áo khoác Bamboo", 320000, "XXL", "Hoodi", 2),
	(55, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần tây Jaco", 280000, "30", "Quần tây", 3),
	(56, "Sản phẩm thoáng mát", "/img/product/3.png", "Quần jean Jaco", 300000, "30", "Quần Jean", 3),
	(57, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_Y", 360000, "XXL", "Quần Jean", 4),
	(58, "Sản phẩm thoáng mát", "/img/product/1.png", "Quần short Jaco_X", 360000, "XXL", "Quần kaki", 4),
	(59, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi JC", 360000, "XL", "Sơ mi tay dài", 5),
	(60, "Sản phẩm thoáng mát", "/img/product/1.png", "Sơ mi KC", 360000, "XXL", "Sơ mi tay ngắn", 5);